apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-platform

resources:
  - control-plane-deployment.yaml
  - control-plane-service.yaml
  - control-plane-hpa.yaml
  - compute-plane-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-platform
